---
# handlers file for mediafellows.filebeat

- name: restart filebeat
  ansible.builtin.service:
    name: filebeat
    state: restarted

- name: clean registry
  ansible.builtin.file:
    path: /var/lib/filebeat/registry/filebeat/
    state: absent
